# Name of the testcase
Configure:
    # Location of the blitz trigger
    source:
      pkg: genie.libs.sdk
      class: triggers.blitz.blitz.Blitz

    # Field containing all the Testcase sections
    test_sections:

        # Section name
        - configure_interface:
            # List of actions
            - configure:
                device: R3_nx
                command: |
                  interface Ethernet2/3
                  ip address 5.5.5.5 255.255.255.0
                  no shutdown
            - configure:
                device: csr1000v-1
                command: |
                  interface Gigabit5
                  ip address 5.5.5.6 255.255.255.0
                  no shutdown

        - verify_interface_configuration:
            # List of actions
            - parse:
                device: R3_nx
                command: show interface
                include:
                  - contains('Ethernet2/3').contains('5.5.5.5/24')
                  - contains('Ethernet2/3').contains_key_value('admin_state', 'up')
            - parse:
                device: csr1000v-1
                command: show interfaces
                include:
                  - contains('Gigabit5').contains('5.5.5.6/24')
                  - contains('Gigabit5').contains_key_value('admin_state', 'up')
